# Generated by Django 3.1.4 on 2021-06-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data_1',
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
