# Generated by Django 3.1.4 on 2021-06-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_descriptio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptio',
        ),
    ]
