# Generated by Django 3.1.4 on 2021-06-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210612_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='h',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
