# Generated by Django 3.1.4 on 2021-06-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='m',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
