# Generated by Django 3.1.4 on 2021-06-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
