# Generated by Django 3.1.4 on 2021-06-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_colors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='mobile_phones',
        ),
    ]
