# Generated by Django 3.1.4 on 2021-06-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210612_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobile_phones',
            new_name='mobile_phone',
        ),
    ]
