# Generated by Django 3.1.4 on 2021-06-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210612_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='lego_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='static')),
                ('price', models.FloatField(max_length=200, null=True)),
                ('section', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('model_no', models.CharField(max_length=200, null=True)),
                ('pieces', models.CharField(max_length=200, null=True)),
                ('dimensions', models.CharField(max_length=200, null=True)),
                ('top', models.CharField(max_length=200, null=True)),
                ('bottom', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
