# Generated by Django 3.1.4 on 2021-06-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_lego_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='static')),
                ('category_1', models.CharField(max_length=200, null=True)),
                ('description_1', models.CharField(max_length=200, null=True)),
                ('image_2', models.ImageField(upload_to='static')),
                ('category_2', models.CharField(max_length=200, null=True)),
                ('description_2', models.CharField(max_length=200, null=True)),
                ('image_3', models.ImageField(upload_to='static')),
                ('category_3', models.CharField(max_length=200, null=True)),
                ('description_3', models.CharField(max_length=200, null=True)),
                ('image_4', models.ImageField(upload_to='static')),
                ('category_4', models.CharField(max_length=200, null=True)),
                ('description_4', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
