# Generated by Django 3.1.4 on 2021-06-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lego_model',
            name='price',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mobile_phone',
            name='price',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
