# Generated by Django 3.1.4 on 2021-06-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210613_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(max_length=200, null=True)),
                ('spec_1', models.CharField(max_length=200, null=True)),
                ('spec_2', models.CharField(max_length=200, null=True)),
                ('spec_3', models.CharField(max_length=200, null=True)),
                ('spec_4', models.CharField(max_length=200, null=True)),
                ('spec_5', models.CharField(max_length=200, null=True)),
                ('model_embed', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
