# Generated by Django 3.1.4 on 2021-06-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='style',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
