# Generated by Django 3.1.4 on 2021-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_categorie_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='mb',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
