# Generated by Django 3.1.4 on 2021-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_clock_mt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='mt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
