# Generated by Django 3.1.4 on 2021-06-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210613_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
