# Generated by Django 3.1.4 on 2021-06-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='view_mobiles',
        ),
    ]
