# Generated by Django 3.1.4 on 2021-06-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210613_2224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='view_mobiles',
            new_name='view_mobile',
        ),
    ]
