# Generated by Django 3.1.4 on 2021-06-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210613_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile_phone',
            name='identity_data',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
