# Generated by Django 3.1.4 on 2021-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_mobile_phone_identity_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile_phone',
            name='identity_data',
        ),
        migrations.AddField(
            model_name='view_mobile',
            name='identity_data',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mobile_phone',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
