# Generated by Django 3.1.4 on 2021-06-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210613_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsheet',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clock',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lego_model',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='view_mobile',
            name='identity_data',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='view_mobile',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
