# Generated by Django 3.1.4 on 2021-06-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210613_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view_mobile',
            name='identity_number',
        ),
    ]
