# Generated by Django 3.1.4 on 2021-06-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_view_mobile_identity_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile_phone',
            name='identity_number',
            field=models.IntegerField(null=True),
        ),
    ]
