# Generated by Django 3.1.4 on 2021-06-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_mobile_phone_identity_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobile_phone',
            new_name='mobile_phones',
        ),
    ]
