# Generated by Django 3.1.4 on 2021-06-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210614_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='static')),
                ('price', models.IntegerField(null=True)),
                ('os', models.CharField(max_length=200, null=True)),
                ('ram', models.CharField(max_length=200, null=True)),
                ('storage', models.CharField(max_length=200, null=True)),
                ('display', models.CharField(max_length=200, null=True)),
                ('battery', models.CharField(max_length=200, null=True)),
                ('colors', models.CharField(max_length=200, null=True)),
                ('h', models.CharField(max_length=200, null=True)),
                ('w', models.CharField(max_length=200, null=True)),
                ('m', models.CharField(max_length=200, null=True)),
                ('identity_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='mobile_phones',
            new_name='mobile_phone',
        ),
    ]
