# Generated by Django 3.1.4 on 2021-06-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210614_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobile_phone',
            new_name='mobile_phones',
        ),
    ]
