# Generated by Django 3.1.4 on 2021-06-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210614_1338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MP',
            new_name='mobile_phone',
        ),
    ]
