# Generated by Django 3.1.4 on 2021-06-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20210614_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile_phone',
            name='identity_number',
        ),
    ]
