# Generated by Django 3.1.4 on 2021-06-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_mobile_phone_identity_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mobile_phones',
        ),
    ]
