# Generated by Django 3.1.4 on 2021-06-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210614_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='view_mobile',
        ),
    ]
