# Generated by Django 3.1.4 on 2021-06-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_delete_view_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile_phone',
            name='current_color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
