# Generated by Django 3.1.4 on 2021-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_mobile_phone_current_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lego_model',
            name='model_image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lego_model',
            name='spec_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lego_model',
            name='spec_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lego_model',
            name='spec_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lego_model',
            name='spec_4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
