# Generated by Django 3.1.4 on 2021-06-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20210614_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lego_model',
            name='model_image',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
