# Generated by Django 3.1.4 on 2021-06-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20210614_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedsheet',
            name='spec_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bedsheet',
            name='spec_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bedsheet',
            name='spec_3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
