# Generated by Django 3.1.4 on 2021-06-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20210614_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='spec_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clock',
            name='spec_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clock',
            name='spec_3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
