# Generated by Django 3.1.4 on 2021-06-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210614_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lego_model',
            name='model_image',
        ),
    ]
