# Generated by Django 3.1.4 on 2021-06-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_remove_lego_model_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lego_model',
            name='model_image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
