# Generated by Django 3.1.4 on 2021-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20210616_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('e_mail', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='add_student',
        ),
    ]
