# Generated by Django 3.1.4 on 2021-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20210616_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us_form',
            name='e_mail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact_us_form',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact_us_form',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
