# Generated by Django 3.1.4 on 2021-06-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20210616_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us_form',
            name='message',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
