# Generated by Django 3.1.4 on 2021-06-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20210616_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile_phone',
            old_name='colors',
            new_name='color_1',
        ),
        migrations.AddField(
            model_name='mobile_phone',
            name='color_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mobile_phone',
            name='color_3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
