# Generated by Django 3.1.4 on 2021-06-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20210616_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile_phone',
            name='current_color',
        ),
    ]
