# Generated by Django 3.1.4 on 2021-06-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20210617_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile_phone',
            name='model_embed_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mobile_phone',
            name='model_embed_3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
