# Generated by Django 3.1.4 on 2021-06-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signup_form',
        ),
    ]
