# Generated by Django 3.1.4 on 2021-06-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blog_data',
        ),
    ]
